### ISSUE TITLE
The Issue of Triton Server Load Same Model Many Times 

### ISSUE THREAD

**Issue by hifanuraydin** [triton-inference-server/server#4987]
why my triton server(v20.12-py3) load my onnx models multiple times?can anyone help me with this issue? @dyastremsky

**Comment by AhmetTpc** [comment]
Same error for me

**Comment by dyastremsky** [comment]
Can you provide the output? Can you try running in a more recent version (the latest is 22.09)? It sounds like it could be a bug, but that version is almost 2 years old and so the bug would likely have been fixed by now.

**Comment by AhmetTpc** [comment]
I send one request  for 5 model but logs have 10 request success. So ı think every model load two times. Am ı wrong?  Why ı have logs like this?

LOGS:

nv_inference_request_success{gpu_uuid="GPU-94be1d54-6a81-e0b7-81e1-21f02744e9d1",model="test_model_1",version="1"} 857877.000000

nv_inference_request_success{gpu_uuid="GPU-94be1d54-6a81-e0b7-81e1-21f02744e9d1",model="test_model_2",version="1"} 1085.000000

nv_inference_request_success{gpu_uuid="GPU-94be1d54-6a81-e0b7-81e1-21f02744e9d1",model="test_model_3",version="1"} 6437.000000

nv_inference_request_success{gpu_uuid="GPU-94be1d54-6a81-e0b7-81e1-21f02744e9d1",model="test_model_4",version="1"} 860681.000000

nv_inference_request_success{gpu_uuid="GPU-94be1d54-6a81-e0b7-81e1-21f02744e9d1",model="test_model_5",version="1"} 1230.000000

nv_inference_request_success{gpu_uuid="GPU-91fef1e8-4c54-f941-2c58-3a3b5ee10d0c",model="test_model_2",version="1"} 1082.000000

nv_inference_request_success{gpu_uuid="GPU-91fef1e8-4c54-f941-2c58-3a3b5ee10d0c",model="test_model_3",version="1"} 6504.000000

nv_inference_request_success{gpu_uuid="GPU-91fef1e8-4c54-f941-2c58-3a3b5ee10d0c",model="test_model_5",version="1"} 1189.000000

nv_inference_request_success{gpu_uuid="GPU-91fef1e8-4c54-f941-2c58-3a3b5ee10d0c",model="test_model_1",version="1"} 863731.000000

nv_inference_request_success{gpu_uuid="GPU-91fef1e8-4c54-f941-2c58-3a3b5ee10d0c",model="test_model_4",version="1"} 861025.000000

**Comment by dyastremsky** [comment]
This doesn't look like it'd be each model loading twice. You can verify that based on the logs (especially in --log-verbose mode), since you can see logs for each model being loaded. Even if your model has 2+ instances, requests and responses don't get duplicated.

You'd need to fill out the bug template to provide exactly what you're running and the full logs. However, this is for a version that's nearly two years old and the bugs may have been fixed. Are you able to use the most recent version of Triton and see if this behavior still exists?

**Comment by hifanuraydin** [comment]
Thanks for your your all answers.I will upgrade my version to the latest one and i'll let you know about that.

**Comment by AhmetTpc** [comment]
I will try to new version (22.09). Then ı will share logs if i still have a bug. Thanks for your help

**Comment by jbkyang-nvi** [comment]
Closing issue due to lack of activity. Please re-open the issue if you would like to follow up with this issue
